export type BestiaryCategory = 'arrakis' | 'dominion' | 'distribute';

export interface BestiaryCreature {
  id: string;
  name: string;
  nombreFremen: string;
  tipo: string;
  descripcion: string;
  tamaño: string;
  habitat: string;
  significancia: string;
}

export const BESTIARY_CATEGORIES: Array<{
  id: BestiaryCategory;
  label: string;
  description: string;
}> = [
  {
    id: 'arrakis',
    label: 'ARRAKIS',
    description: 'Criaturas Nativas del Desierto',
  },
  {
    id: 'dominion',
    label: 'DOMINION',
    description: 'Ingenierizado y Controlado',
  },
  {
    id: 'distribute',
    label: 'DISTRIBUIR',
    description: 'Diverso Multi-Mundo',
  },
];

export const CREATURE_IMAGE_MAP: Record<string, string> = {
  shai_hulud: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/shai-hulud-pixel-5WJWH8wzQJfM9s9kdgdPas.webp',
  muad_dib: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/muad-dib-pixel-d5Nn6Rwya6WSAwDgEm5fKB.webp',
  cielago: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/cielago-pixel-TJ7yfjzUWGwhuAixCqsNNk.webp',
  desert_hawk: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/desert-hawk-pixel-M546w7hCjPz87anEENZ6r8.webp',
  kit_fox: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/kit-fox-pixel-7qEACZ4BBAQ4YkZSnqG6Db.webp',
  scorpion: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/scorpion-pixel-ELPXctcWjjJU3XZYmfHJns.webp',
  trapdoor_spider: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/spider-pixel-Aufb7HKsqboDepuFxbJH6y.webp',
  desert_hare: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/desert-hare-pixel-XXUxH4YMoyyaGWQLdzWuTC.webp',
  laza_tiger: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/laza-tiger-pixel-gAA4Bia58LxnauZukYrRNz.webp',
  seaworm: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/seaworm-pixel-VwzuDQ4BwiZ945yRDfJZuh.webp',
  chairdog: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/chairdog-pixel-QeEXhzp8Vcuf3Xi7jAYBpA.webp',
  slig: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/slig-pixel-mTVyh8ydBUaPMS2xd5hkca.webp',
  sand_terrapin: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/sand-terrapin-pixel-dwjEthiWGF5H5Bzmh4kUoF.webp',
  wormfly: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/wormfly-pixel-DMW3VpD7pivwJEsoirWBf9.webp',
  eagle: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/eagle-pixel-ABWcWG8u9QTRKHj9vzBV2V.webp',
  desert_owl: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/desert-owl-pixel-DW7BdwHudBjDx2M9gYyakH.webp',
  centipede: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/centipede-pixel-mZThoY2U9jeDpAnR5Evhxr.webp',
  bull: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/bull-pixel-nMJeUxgi63XaNhJ95XYgfA.webp',
  dwarf_owl: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/desert-owl-pixel-DW7BdwHudBjDx2M9gYyakH.webp',
  sandtrout: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/seaworm-pixel-VwzuDQ4BwiZ945yRDfJZuh.webp',
  little_maker: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663452877580/Tj6E9GfbunnYfScJdesLtv/seaworm-pixel-VwzuDQ4BwiZ945yRDfJZuh.webp',
};

export const BESTIARY_CREATURES: Record<BestiaryCategory, BestiaryCreature[]> = {
  arrakis: [
    {
      id: 'shai_hulud',
      name: 'Shai-Hulud',
      nombreFremen: 'El Dios del Desierto',
      tipo: 'Gusano de Arena',
      descripcion: 'Gusanos de arena masivos e inteligentes que dominan Arrakis. Los Fremen los veneran como seres divinos. Producen la especia melange a través de su ciclo de vida.',
      tamaño: 'Hasta 400+ metros de largo (adulto)',
      habitat: 'Arenas profundas del desierto',
      significancia: 'Sagrado para los Fremen, fuente de especia',
    },
    {
      id: 'muad_dib',
      name: "Muad'Dib",
      nombreFremen: 'Ratón del Desierto',
      tipo: 'Ratón Canguro',
      descripcion: 'Pequeño roedor del desierto que salta y sobrevive creando su propia agua viajando de noche. Símbolo de supervivencia y adaptación.',
      tamaño: 'Pequeño roedor',
      habitat: 'Superficie del desierto',
      significancia: 'Símbolo de Paul Atreides, representa la supervivencia del desierto',
    },
    {
      id: 'cielago',
      name: 'Ciélago',
      nombreFremen: 'Murciélago del Desierto',
      tipo: 'Murciélago',
      descripcion: 'Mamíferos voladores adaptados a la oscuridad de Arrakis. Utilizados por los Fremen para transportar mensajes mediante dispositivos Distrans.',
      tamaño: 'Pequeño',
      habitat: 'Cuevas subterráneas y cielos nocturnos',
      significancia: 'Portadores de mensajes Fremen',
    },
    {
      id: 'desert_hawk',
      name: 'Halcón del Desierto',
      nombreFremen: 'Depredador del Cielo',
      tipo: 'Ave Rapaz',
      descripcion: 'Feroz depredador aéreo adaptado a la caza en el desierto. Caza pequeñas criaturas a través de las dunas.',
      tamaño: 'Ave mediana',
      habitat: 'Cielos del desierto',
      significancia: 'Depredador ápice de criaturas pequeñas',
    },
    {
      id: 'kit_fox',
      name: 'Zorro del Desierto',
      nombreFremen: 'Zorro de Arena',
      tipo: 'Cánido',
      descripcion: 'Pequeño zorro del desierto adaptado a temperaturas extremas. Parte del ecosistema ingenierizado de Arrakis.',
      tamaño: 'Pequeño',
      habitat: 'Superficie del desierto y madrigueras',
      significancia: 'Participante del ecosistema de Arrakis',
    },
    {
      id: 'desert_hare',
      name: 'Liebre del Desierto',
      nombreFremen: 'Liebre de Arena',
      tipo: 'Lagomorfo',
      descripcion: 'Liebre rápida del desierto cazada por alimento. La liebre asada del desierto es un plato popular en Arrakis.',
      tamaño: 'Pequeña',
      habitat: 'Superficie del desierto',
      significancia: 'Fuente de alimento para los Fremen',
    },
    {
      id: 'sand_terrapin',
      name: 'Tortuga de Arena',
      nombreFremen: 'Tortuga del Desierto',
      tipo: 'Reptil',
      descripcion: 'Reptil blindado del desierto que se entierra en la arena. Altamente adaptado al calor extremo.',
      tamaño: 'Pequeña a mediana',
      habitat: 'Arena del desierto',
      significancia: 'Participante del ecosistema',
    },
    {
      id: 'scorpion',
      name: 'Escorpión',
      nombreFremen: 'Escorpión de Arena',
      tipo: 'Arácnido',
      descripcion: 'Escorpión venenoso del desierto. Mortal para los viajeros desprevenidos.',
      tamaño: 'Pequeño',
      habitat: 'Arena y rocas del desierto',
      significancia: 'Peligro del desierto',
    },
  ],
  dominion: [
    {
      id: 'laza_tiger',
      name: 'Tigre Laza',
      nombreFremen: 'Bestia Ingenierizada',
      tipo: 'Felino Genéticamente Modificado',
      descripcion: 'Tigre genéticamente modificado equipado con dispositivos de control remoto. Utilizado como arma por las fuerzas de la Casa.',
      tamaño: 'Depredador grande',
      habitat: 'Instalaciones de entrenamiento y zonas de combate',
      significancia: 'Arma de la Casa Harkonnen',
    },
    {
      id: 'chairdog',
      name: 'Perro-Silla',
      nombreFremen: 'Mueble Viviente',
      tipo: 'Cánido Genéticamente Modificado',
      descripcion: 'Creación genética grotesca que sirve como mueble viviente. Representa el dominio biotecnológico de los Tleilaxu.',
      tamaño: 'Grande',
      habitat: 'Casas nobles',
      significancia: 'Símbolo del dominio genético Tleilaxu',
    },
    {
      id: 'slig',
      name: 'Slig',
      nombreFremen: 'Abominación Genética',
      tipo: 'Criatura Ingenierizada',
      descripcion: 'Criatura bizarra creada por los Tleilaxu. Utilizada para varios propósitos por el Imperio.',
      tamaño: 'Variable',
      habitat: 'Instalaciones Tleilaxu',
      significancia: 'Producto de ingeniería genética extrema',
    },
    {
      id: 'sandtrout',
      name: 'Gusano de Arena Joven',
      nombreFremen: 'Creador Joven',
      tipo: 'Gusano de Arena Larval',
      descripcion: 'Forma larval del gusano de arena. Produce agua en lugar de especia. Peligroso de manipular.',
      tamaño: 'Pequeño a mediano',
      habitat: 'Desierto profundo',
      significancia: 'Estadio larval de Shai-Hulud',
    },
    {
      id: 'little_maker',
      name: 'Pequeño Creador',
      nombreFremen: 'Gusano Infantil',
      tipo: 'Gusano de Arena Juvenil',
      descripcion: 'Etapa joven del gusano de arena. Altamente peligroso a pesar de su pequeño tamaño.',
      tamaño: 'Pequeño',
      habitat: 'Desierto',
      significancia: 'Desarrollo temprano del gusano de arena',
    },
  ],
  distribute: [
    {
      id: 'eagle',
      name: 'Águila',
      nombreFremen: 'Señor del Cielo',
      tipo: 'Ave Rapaz',
      descripcion: 'Majestuosa ave rapaz encontrada en múltiples mundos. Símbolo de nobleza.',
      tamaño: 'Ave grande',
      habitat: 'Cielos de múltiples planetas',
      significancia: 'Símbolo universal de depredador',
    },
    {
      id: 'desert_owl',
      name: 'Búho del Desierto',
      nombreFremen: 'Cazador Nocturno',
      tipo: 'Ave Nocturna',
      descripcion: 'Depredador nocturno adaptado a la oscuridad. Caza pequeñas criaturas durante la noche.',
      tamaño: 'Ave mediana',
      habitat: 'Noche del desierto',
      significancia: 'Depredador nocturno',
    },
    {
      id: 'dwarf_owl',
      name: 'Búho Enano',
      nombreFremen: 'Pequeño Vigilante Nocturno',
      tipo: 'Ave Nocturna Pequeña',
      descripcion: 'Variante más pequeña del búho del desierto. Adaptada a condiciones extremas del desierto.',
      tamaño: 'Ave pequeña',
      habitat: 'Desierto',
      significancia: 'Depredador en miniatura',
    },
    {
      id: 'centipede',
      name: 'Ciempiés',
      nombreFremen: 'De Muchas Patas',
      tipo: 'Artrópodo',
      descripcion: 'Ciempiés grande del desierto. Depredador peligroso de criaturas pequeñas.',
      tamaño: 'Artrópodo mediano',
      habitat: 'Arena y rocas del desierto',
      significancia: 'Depredador del desierto',
    },
    {
      id: 'trapdoor_spider',
      name: 'Araña Trampa',
      nombreFremen: 'Atrapador de Arena',
      tipo: 'Arácnido',
      descripcion: 'Depredador de emboscada que crea madrigueras trampa en la arena.',
      tamaño: 'Pequeña',
      habitat: 'Arena del desierto',
      significancia: 'Cazador de emboscada',
    },
    {
      id: 'wormfly',
      name: 'Mosca del Gusano',
      nombreFremen: 'Mosca de Especia',
      tipo: 'Insecto',
      descripcion: 'Insecto volador atraído por la especia. Indicador de presencia de especia.',
      tamaño: 'Diminuto',
      habitat: 'Aire del desierto',
      significancia: 'Indicador de especia',
    },
    {
      id: 'seaworm',
      name: 'Gusano Marino',
      nombreFremen: 'Gusano de Agua',
      tipo: 'Gusano Acuático',
      descripcion: 'Criatura similar a gusano de mundos acuáticos. Paralelo a los gusanos de arena de Arrakis.',
      tamaño: 'Grande',
      habitat: 'Cuerpos de agua en otros planetas',
      significancia: 'Equivalente acuático del gusano de arena',
    },
    {
      id: 'bull',
      name: 'Toro',
      nombreFremen: 'Bestia Cornuda',
      tipo: 'Bóvido',
      descripcion: 'Bestia domesticada grande. Utilizada para transporte y trabajo.',
      tamaño: 'Grande',
      habitat: 'Tierras de pastoreo',
      significancia: 'Animal de trabajo',
    },
  ],
};
